### ISSUE TITLE
Internet not working

### ISSUE THREAD

**Issue by ramymoh** [itsnebulalol/betterblock#1]
Starting from today internet stop working on my iPhone. Only working when i disable betterblock DNS. so please check

**Comment by itsnebulalol** [comment]
I'm sorry! It's a current issue with my server, I updated and it stopped working, even if I reinstalled it.
I'll get it working as soon as possible

**Comment by itsnebulalol** [comment]
EDIT: https://twitter.com/itsnebulalol/status/1504820924486496256?s=21
